/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_example_seriznue_svdl_app_OpencvNativeClass */

#ifndef _Included_com_example_seriznue_svdl_app_OpencvNativeClass
#define _Included_com_example_seriznue_svdl_app_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_seriznue_svdl_app_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_example_seriznue_svdl_1app_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
